SCR_MapConfig {
 m_iMapMode FULLSCREEN
 m_LayersConfig SCR_MapLayersBase "{58C8DDC97E580BED}" : "{3CAC09C3E89190F7}Configs/Map/MapLayersDefault.conf" {
 }
 m_MapPropsConfig SCR_MapPropsBase "{58C89E75E1BB275D}" : "{AF65563F653FED68}Configs/Map/MapPropsDefault.conf" {
 }
 m_aModules {
  SCR_MapCursorModule "{6985327711306100}" : "{5E40C9235FDA4430}Configs/Map/Prefabs/MapCursorModuleDef.conf" {
   m_bEnableCrosshairCoords 1
   m_bEnableCursorEdgePan 0
   m_bIsCursorCenteredOnOpen 0
  }
 }
 m_aUIComponents {
  SCR_MapRadialUI "{5C9AA3F59815B7D6}" {
   m_RadialController SCR_RadialMenuController "{5C9AA3F5906CC626}" {
    m_RMControls SCR_RadialMenuControllerInputs "{5C9AA3F5964C8665}" {
     m_bCloseOnReleaseOpen 0
     m_bPerformOnClose 0
     m_bCloseOnPerform 1
    }
    m_Data SCR_SelectionMenuData "{5C9AA3F5699E1B06}" {
    }
   }
   m_RadialMenu SCR_RadialMenu "{5D9A83188B57DA4B}" : "{D9448EF097CB0ACB}Configs/HUD/RadialMenu/GlobalRadialMenu.conf" {
   }
  }
  SCR_MapCampaignUI "{5510976DEBFC5555}" {
  }
  SCR_MapLightUI "{5510976DEC9A88DC}" {
  }
  SCR_MapToolInteractionUI "{59B6C77F84908AC3}" {
  }
  SCR_MapWatchUI "{55BC7CDB3688D5F0}" {
   m_aSizesArray {
    ToolSize "{59D6CDCE8EF8F2CC}" {
     m_iSizeX 150
     m_iSizeY 187
    }
    ToolSize "{59D6CDCE807099A9}" {
     m_iSizeX 250
     m_iSizeY 312
    }
   }
  }
  SCR_MapDebugUI "{59028015752E91BE}" {
   m_fUnitIconRotation -90
  }
  SCR_MapRulerUI "{5EB0852B02C40995}" : "{7884D3EDB4762263}Configs/Map/Prefabs/MapRulerUIDef.conf" {
  }
  SCR_MapToolMenuUI "{599C7D68E8F6B9A8}" {
  }
  SCR_MapTaskListUI "{59A0E8386D3EC558}" {
   m_bIsExclusive 1
  }
  SCR_MapDrawingUI "{59BA7DF39A56CF16}" {
  }
  SCR_MapMarkersUI "{5D08A0A3CB302C30}" {
  }
  SCR_MapCompassUI "{5E88A0BAA9983F29}" : "{D1282B3EA205074A}Configs/Map/Prefabs/MapCompassUIDef.conf" {
  }
  SCR_MapJournalUI "{61026342C640434C}" {
   m_bIsExclusive 1
  }
  SCR_MapWeatherUI "{68ACAA2DB3AE170A}" {
  }
 }
 m_bEnableLegendScale 1
 m_DescriptorVisibilityConfig SCR_MapDescriptorVisibilityBase "{58C8DDC9087BF565}" : "{4FFDB559B60FC7BC}Configs/Map/MapDescriptorVisibilityDefault.conf" {
 }
 m_DescriptorDefaultsConfig SCR_MapDescriptorDefaults "{58C89E6280B692A8}" : "{FF6B20825D4A566C}Configs/Map/MapDescriptorDefaults.conf" {
 }
}
