SCR_MapMarkerConfig : "{3583D42139D9A10B}Configs/Map/CampaignMapMarkerConfig.conf" {
 m_aMarkerEntryConfigs {
  SCR_MapMarkerEntrySquadLeader "{5DDAE75E563127AA}" {
   m_sMarkerPrefab "{9DEFDDD21D8D3891}Prefabs/Markers/CampaignHQCMapMarkerSquadLeader.et"
  }
  SCR_MapMarkerEntrySquadMember "{66EAD91F4EC2FB46}" {
   m_sMarkerLayout "{0CF9A6FB588EB475}UI/layouts/Map/MapMarkerSquadMember.layout"
   m_sMarkerPrefab "{E250A3D57FDDB29B}Prefabs/Markers/MapMarkerSquadMember.et"
  }
  HST_PlayerMapMarkerEntry "{6985327711306213}" {
   m_sMarkerLayout "{6985327711306214}UI/layouts/HST/Map/HST_PlayerMapMarkerDynamic.layout"
   m_sMarkerPrefab "{6985327711306230}Prefabs/Markers/HST_PlayerMapMarker.et"
  }
 }
}
