SCR_MapMarkerConfig : "{3583D42139D9A10B}Configs/Map/CampaignMapMarkerConfig.conf" {
 m_aMarkerEntryConfigs {
  HST_PlayerMapMarkerEntry "{6985327711306213}" {
   m_sMarkerLayout "{0CF9A6FB588EB475}UI/layouts/Map/MapMarkerSquadMember.layout"
   m_sMarkerPrefab "{DD74BE2BBAE07192}Prefabs/Markers/MapMarkerEntityBase.et"
  }
 }
}
