SCR_MapConfig {
 m_iMapMode FULLSCREEN
 m_LayersConfig SCR_MapLayersBase "{58C8DDC97E580BED}" : "{3CAC09C3E89190F7}Configs/Map/MapLayersDefault.conf" {
 }
 m_MapPropsConfig SCR_MapPropsBase "{58C89E75E1BB275D}" : "{AF65563F653FED68}Configs/Map/MapPropsDefault.conf" {
 }
 m_aModules {
  SCR_MapCursorModule "{6985327711306100}" : "{5E40C9235FDA4430}Configs/Map/Prefabs/MapCursorModuleDef.conf" {
   m_bEnableCrosshairCoords 1
   m_bEnableCursorEdgePan 0
   m_bIsCursorCenteredOnOpen 0
  }
 }
 m_aUIComponents {
 }
 m_bEnableLegendScale 1
 m_DescriptorVisibilityConfig SCR_MapDescriptorVisibilityBase "{58C8DDC9087BF565}" : "{4FFDB559B60FC7BC}Configs/Map/MapDescriptorVisibilityDefault.conf" {
 }
 m_DescriptorDefaultsConfig SCR_MapDescriptorDefaults "{58C89E6280B692A8}" : "{FF6B20825D4A566C}Configs/Map/MapDescriptorDefaults.conf" {
 }
}
