SystemSettings : "{1C60D2EDA2B468B8}Configs/Systems/BaseGameModeSystems.conf" {
 Systems {
  SCR_PersistenceSystem "{3D480BF81D624698}" {
   SystemLocation Server
   SystemPoints 0x2000 0x10
   Config "{B81394D619F646E2}Configs/HST/Persistence/HST_CampaignPersistence.conf"
  }
 }
}
