PersistenceSystemConfig : "{BEFFBD9A87620F23}Configs/Systems/Persistence/BaseSetup.conf" {
 Configurations {
  PersistenceConfigGroup ScriptedStates {
   Configurations {
    PersistenceConfigGroup Campaign {
     Configurations {
      ScriptedStatePersistenceConfig "{225731FAE96642CA}" {
       Collection "{6586D01E488CA578}"
       SelfDelete 0
       Serializer HST_CampaignPersistentStateSerializer "{034300F12BE5436B}" {
       }
      }
     }
    }
   }
  }
 }
 PersistentStates {
  HST_CampaignPersistentState "{50CE4BFB1EBD4844}" {
  }
 }
}
