HST_FactionTemplate {
 m_sTemplateId "ussr_invader"
 m_sFactionKey "USSR"
 m_sDisplayName "USSR Invaders"
 m_aCapabilities {
  "infantry"
  "light_vehicles"
  "qrf"
 }
 m_aVehiclePrefabs {
  "Prefabs/Vehicles/Wheeled/UAZ469/UAZ469.et"
  "Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_PKM.et"
  "Prefabs/Vehicles/Wheeled/Ural4320/Ural4320.et"
  "Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_transport.et"
 }
 m_aGroupPrefabs {
  "{E552DABF3636C2AD}Prefabs/Groups/OPFOR/Group_USSR_RifleSquad.et"
  "{30ED11AA4F0D41E5}Prefabs/Groups/OPFOR/Group_USSR_FireGroup.et"
 }
 m_aPatrolGroupPrefabs {
  "{CB58D90EA14430AD}Prefabs/Groups/OPFOR/Group_USSR_SentryTeam.et"
  "{30ED11AA4F0D41E5}Prefabs/Groups/OPFOR/Group_USSR_FireGroup.et"
 }
 m_aQRFGroupPrefabs {
  "{E552DABF3636C2AD}Prefabs/Groups/OPFOR/Group_USSR_RifleSquad.et"
  "{A2F75E45C66B1C0A}Prefabs/Groups/OPFOR/Group_USSR_MachineGunTeam.et"
 }
 m_aSupportIds {
  "support_mortar"
 }
}
