HST_FactionTemplate {
 m_sTemplateId "fia_resistance"
 m_sFactionKey "FIA"
 m_sDisplayName "FIA Resistance"
 m_bPlayable 1
 m_aCapabilities {
  "infantry"
  "light_vehicles"
  "hideouts"
  "weapon_caches"
  "air_support_unlockable"
 }
 m_aVehiclePrefabs {
  "Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_FIA_transport.et"
 }
 m_aGroupPrefabs {
  "Prefabs/Groups/INDFOR/Group_FIA_RifleSquad.et"
  "Prefabs/Groups/INDFOR/FIA/Group_FIA_RifleSquad.et"
 }
 m_aPatrolGroupPrefabs {
  "Prefabs/Groups/INDFOR/Group_FIA_SentryTeam.et"
  "Prefabs/Groups/INDFOR/Group_FIA_FireGroup.et"
 }
 m_aQRFGroupPrefabs {
  "Prefabs/Groups/INDFOR/Group_FIA_RifleSquad.et"
  "Prefabs/Groups/INDFOR/FIA/Group_FIA_RifleSquad.et"
 }
 m_aSupportIds {
  "support_mortar"
 }
}
