HST_FactionTemplate {
 m_sTemplateId "us_occupier"
 m_sFactionKey "US"
 m_sDisplayName "US Occupiers"
 m_aCapabilities {
  "infantry"
  "light_vehicles"
  "qrf"
 }
 m_aVehiclePrefabs {
  "{4A71F755A4513227}Prefabs/Vehicles/Wheeled/M998/M1025.et"
  "Prefabs/Vehicles/Wheeled/M151A2/M151A2.et"
 }
 m_aGroupPrefabs {
  "{8B4D49A9F324E7D5}Prefabs/Groups/PlayableGroup.et"
 }
 m_aPatrolGroupPrefabs {
  "{8B4D49A9F324E7D5}Prefabs/Groups/PlayableGroup.et"
 }
 m_aQRFGroupPrefabs {
  "{8B4D49A9F324E7D5}Prefabs/Groups/PlayableGroup.et"
 }
 m_aSupportIds {
  "support_mortar"
 }
}
