HST_FactionTemplate {
 m_sTemplateId "us_occupier"
 m_sFactionKey "US"
 m_sDisplayName "US Occupiers"
 m_aCapabilities {
  "infantry"
  "light_vehicles"
  "qrf"
 }
 m_aVehiclePrefabs {
  "{4A71F755A4513227}Prefabs/Vehicles/Wheeled/M998/M1025.et"
 }
 m_aGroupPrefabs {
  "{412A7767B11310C5}Prefabs/Groups/Campaign/Group_US.et"
  "Prefabs/Groups/BLUFOR/Group_US_RifleSquad.et"
 }
 m_aPatrolGroupPrefabs {
  "{412A7767B11310C5}Prefabs/Groups/Campaign/Group_US.et"
  "Prefabs/Groups/BLUFOR/Group_US_SentryTeam.et"
 }
 m_aQRFGroupPrefabs {
  "{412A7767B11310C5}Prefabs/Groups/Campaign/Group_US.et"
  "Prefabs/Groups/BLUFOR/Group_US_RifleSquad.et"
 }
 m_aSupportIds {
  "support_mortar"
 }
}
