HST_FactionTemplate {
 m_sTemplateId "ussr_invader"
 m_sFactionKey "USSR"
 m_sDisplayName "USSR Invaders"
 m_aCapabilities {
  "infantry"
  "light_vehicles"
  "qrf"
 }
 m_aVehiclePrefabs {
  "Prefabs/Vehicles/Wheeled/UAZ469/UAZ469.et"
  "Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_PKM.et"
  "Prefabs/Vehicles/Wheeled/Ural4320/Ural4320.et"
  "Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_transport.et"
 }
 m_aGroupPrefabs {
  "{CB08A3832252F5B9}Prefabs/Groups/OPFOR/AmbientPatrols/Group_USSR_MortarTeam_NotSpawned.et"
 }
 m_aPatrolGroupPrefabs {
  "{CB08A3832252F5B9}Prefabs/Groups/OPFOR/AmbientPatrols/Group_USSR_MortarTeam_NotSpawned.et"
 }
 m_aQRFGroupPrefabs {
  "{CB08A3832252F5B9}Prefabs/Groups/OPFOR/AmbientPatrols/Group_USSR_MortarTeam_NotSpawned.et"
 }
 m_aSupportIds {
  "support_mortar"
 }
}
