HST_FactionTemplate {
 m_sTemplateId "fia_resistance"
 m_sFactionKey "FIA"
 m_sDisplayName "FIA Resistance"
 m_bPlayable 1
 m_aCapabilities {
  "infantry"
  "light_vehicles"
  "hideouts"
  "weapon_caches"
  "air_support_unlockable"
 }
 m_aVehiclePrefabs {
  "Prefabs/Vehicles/Wheeled/M151A2/M151A2.et"
  "Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_FIA_transport.et"
 }
 m_aGroupPrefabs {
  "{8B4D49A9F324E7D5}Prefabs/Groups/PlayableGroup.et"
 }
 m_aPatrolGroupPrefabs {
  "{8B4D49A9F324E7D5}Prefabs/Groups/PlayableGroup.et"
 }
 m_aQRFGroupPrefabs {
  "{8B4D49A9F324E7D5}Prefabs/Groups/PlayableGroup.et"
 }
 m_aSupportIds {
  "support_gbu"
  "support_umpk"
 }
}
