HST_FactionTemplate {
 m_sTemplateId "rhs_usmc_occupier"
 m_sFactionKey "RHS_USAF"
 m_sDisplayName "RHS USMC Occupiers"
 m_aCapabilities {
  "infantry"
  "light_vehicles"
 "armored_vehicles"
 "helicopters"
 "qrf"
 }
 m_aVehiclePrefabs {
  "{4A71F755A4513227}Prefabs/Vehicles/Wheeled/M998/M1025.et"
  "Prefabs/Vehicles/Wheeled/M998/M1025_USAF.et"
  "Prefabs/Vehicles/Wheeled/M998/M1025_armed_M2HB_USAF.et"
 }
 m_aGroupPrefabs {
  "{19843E954790DF28}Prefabs/Groups/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Group_USAF_USMC_MEF_FireTeam.et"
  "{F831DFB4A9B46152}Prefabs/Groups/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Group_USAF_USMC_MEF_RifleSquad.et"
  "{0E3DC6A52A5F959E}Prefabs/Groups/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Group_USAF_USMC_MEF_PlatoonHQ.et"
 }
 m_aPatrolGroupPrefabs {
  "{19843E954790DF28}Prefabs/Groups/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Group_USAF_USMC_MEF_FireTeam.et"
  "{7A43006F3F254FB2}Prefabs/Groups/BLUFOR/RHS_USAF/RHS_USAF_MARSOC/Group_USAF_USMC_MARSOC_SentryTeam.et"
 }
 m_aQRFGroupPrefabs {
  "{F831DFB4A9B46152}Prefabs/Groups/BLUFOR/RHS_USAF/RHS_USAF_USMC_MEF/Group_USAF_USMC_MEF_RifleSquad.et"
  "{D31888A77B1C4310}Prefabs/Groups/BLUFOR/RHS_USAF/RHS_USAF_FORECON/Group_USAF_USMC_FORECON_Squad.et"
 }
}
