HST_CampaignPreset {
 m_sPresetId "vanilla_everon"
 m_sDisplayName "Partisan: Everon - FIA vs US vs USSR"
 m_sResistanceFactionKey "FIA"
 m_sOccupierFactionKey "US"
 m_sInvaderFactionKey "USSR"
 m_sBalanceConfig "Configs/HST/Balance/HST_CE311_Balance.conf"
 m_sMapDefinition "Configs/HST/Maps/HST_Everon.conf"
 m_sMissionRegistry "Configs/HST/Missions/HST_CE311_Missions.conf"
 m_aUnavailableCapabilities {
  "fixed_wing_aircraft"
  "sead"
  "artillery"
 }
}
