enum HST_ECampaignPhase
{
	HST_CAMPAIGN_SETUP,
	HST_CAMPAIGN_ACTIVE,
	HST_CAMPAIGN_WON,
	HST_CAMPAIGN_LOST
}

enum HST_EZoneType
{
	HST_ZONE_TOWN,
	HST_ZONE_OUTPOST,
	HST_ZONE_RESOURCE,
	HST_ZONE_FACTORY,
	HST_ZONE_RADIO_TOWER,
	HST_ZONE_AIRFIELD,
	HST_ZONE_SEAPORT,
	HST_ZONE_POLICE_STATION,
	HST_ZONE_BANK,
	HST_ZONE_HIDEOUT,
	HST_ZONE_MISSION_SITE
}

enum HST_EMissionCategory
{
	HST_MISSION_ASSASSINATION,
	HST_MISSION_CONQUEST,
	HST_MISSION_CONVOY,
	HST_MISSION_DESTROY,
	HST_MISSION_LOGISTICS,
	HST_MISSION_RESCUE,
	HST_MISSION_DYNAMIC,
	HST_MISSION_SUPPORT
}

enum HST_EMissionStatus
{
	HST_MISSION_AVAILABLE,
	HST_MISSION_ACTIVE,
	HST_MISSION_SUCCEEDED,
	HST_MISSION_FAILED,
	HST_MISSION_EXPIRED
}

enum HST_EMissionRuntimeMode
{
	HST_MISSION_RUNTIME_ABSTRACT,
	HST_MISSION_RUNTIME_PHYSICAL_MVP,
	HST_MISSION_RUNTIME_STATE_MACHINE
}

enum HST_EGeneratedSiteType
{
	HST_SITE_TOWN_CENTER,
	HST_SITE_OUTPOST,
	HST_SITE_RESOURCE,
	HST_SITE_FACTORY,
	HST_SITE_RADIO,
	HST_SITE_AIRFIELD,
	HST_SITE_SEAPORT,
	HST_SITE_ROADBLOCK,
	HST_SITE_STASH,
	HST_SITE_CRASHSITE,
	HST_SITE_PATROL,
	HST_SITE_SUPPORT
}

enum HST_EMissionObjectiveType
{
	HST_OBJECTIVE_CLEAR_AREA,
	HST_OBJECTIVE_KILL_TARGET,
	HST_OBJECTIVE_DESTROY_TARGET,
	HST_OBJECTIVE_RECOVER_LOOT,
	HST_OBJECTIVE_DELIVER_SUPPLIES,
	HST_OBJECTIVE_RESCUE_CAPTIVES,
	HST_OBJECTIVE_HOLD_AREA,
	HST_OBJECTIVE_FIND_SITE
}

enum HST_ESupportRequestType
{
	HST_SUPPORT_QRF,
	HST_SUPPORT_PATROL_SWEEP,
	HST_SUPPORT_TRANSPORT,
	HST_SUPPORT_SUPPLY_DROP,
	HST_SUPPORT_SEARCH_AND_DESTROY,
	HST_SUPPORT_SUPPRESSIVE_FIRE,
	HST_SUPPORT_TROOP_LANDING,
	HST_SUPPORT_EVACUATION,
	HST_SUPPORT_AIRSTRIKE_GBU,
	HST_SUPPORT_AIRSTRIKE_UMPK,
	HST_SUPPORT_CRUISE_MISSILE_KH55,
	HST_SUPPORT_ROADBLOCK
}

enum HST_ESupportRequestStatus
{
	HST_SUPPORT_QUEUED,
	HST_SUPPORT_ACTIVE,
	HST_SUPPORT_RESOLVED,
	HST_SUPPORT_CANCELLED
}

enum HST_EEnemyOrderType
{
	HST_ENEMY_ORDER_PATROL,
	HST_ENEMY_ORDER_ROADBLOCK,
	HST_ENEMY_ORDER_QRF,
	HST_ENEMY_ORDER_REBUILD_GARRISON,
	HST_ENEMY_ORDER_COUNTERATTACK,
	HST_ENEMY_ORDER_PETROS_ATTACK,
	HST_ENEMY_ORDER_SUPPORT_CALL
}

enum HST_EEnemyOrderStatus
{
	HST_ENEMY_ORDER_QUEUED,
	HST_ENEMY_ORDER_ACTIVE,
	HST_ENEMY_ORDER_RESOLVED,
	HST_ENEMY_ORDER_ABORTED
}

enum HST_EUndercoverStatus
{
	HST_UNDERCOVER_CLEAR,
	HST_UNDERCOVER_SUSPICIOUS,
	HST_UNDERCOVER_COMPROMISED,
	HST_UNDERCOVER_WANTED
}

enum HST_ECampaignCommandStatus
{
	HST_COMMAND_PENDING,
	HST_COMMAND_APPLIED,
	HST_COMMAND_REJECTED,
	HST_COMMAND_ALREADY_APPLIED,
	HST_COMMAND_CONFLICT
}

enum HST_EResourceTransactionStatus
{
	HST_TRANSACTION_RESERVED,
	HST_TRANSACTION_COMMITTED,
	HST_TRANSACTION_PARTIALLY_REFUNDED,
	HST_TRANSACTION_REFUNDED,
	HST_TRANSACTION_CANCELLED
}

enum HST_EForceQuoteStatus
{
	HST_FORCE_QUOTE_ISSUED,
	HST_FORCE_QUOTE_ACCEPTED,
	HST_FORCE_QUOTE_EXPIRED,
	HST_FORCE_QUOTE_REJECTED,
	HST_FORCE_QUOTE_CANCELLED
}

enum HST_EForceSpawnSlotStatus
{
	HST_FORCE_SLOT_QUEUED,
	HST_FORCE_SLOT_REGISTERED,
	HST_FORCE_SLOT_DEFERRED,
	HST_FORCE_SLOT_FAILED_RETRYABLE,
	HST_FORCE_SLOT_FAILED_FINAL,
	HST_FORCE_SLOT_CANCELLED,
	HST_FORCE_SLOT_SPAWNING,
	HST_FORCE_SLOT_CLEANUP_PENDING,
	HST_FORCE_SLOT_RETIRED
}

enum HST_EForceSpawnBatchStatus
{
	HST_FORCE_SPAWN_PENDING,
	HST_FORCE_SPAWN_SUCCEEDED,
	HST_FORCE_SPAWN_DEFERRED,
	HST_FORCE_SPAWN_FAILED_RETRYABLE,
	HST_FORCE_SPAWN_FAILED_FINAL,
	HST_FORCE_SPAWN_CANCELLED,
	HST_FORCE_SPAWN_IN_PROGRESS,
	HST_FORCE_SPAWN_CLEANUP_PENDING,
	HST_FORCE_SPAWN_READY_FOR_HANDOFF
}

enum HST_EOperationType
{
	HST_OPERATION_TYPE_UNKNOWN,
	HST_OPERATION_TYPE_PLAYER_SUPPORT_QRF,
	HST_OPERATION_TYPE_ENEMY_DEFENSIVE_QRF,
	HST_OPERATION_TYPE_MISSION_CONVOY,
	HST_OPERATION_TYPE_ENEMY_PATROL,
	HST_OPERATION_TYPE_GARRISON_PATROL,
	HST_OPERATION_TYPE_MISSION_GUARD,
	HST_OPERATION_TYPE_MISSION_RESCUE,
	HST_OPERATION_TYPE_PLAYER_SUPPORT_SEARCH_DESTROY,
	HST_OPERATION_TYPE_LOCAL_SECURITY_PATROL
}

enum HST_EConvoyElementDisposition
{
	HST_CONVOY_ELEMENT_DISPOSITION_UNKNOWN,
	HST_CONVOY_ELEMENT_DISPOSITION_ACTIVE,
	HST_CONVOY_ELEMENT_DISPOSITION_ABANDONED,
	HST_CONVOY_ELEMENT_DISPOSITION_DESTROYED,
	HST_CONVOY_ELEMENT_DISPOSITION_CAPTURED,
	HST_CONVOY_ELEMENT_DISPOSITION_ARRIVED,
	HST_CONVOY_ELEMENT_DISPOSITION_RETIRED
}

enum HST_ERescueCaptiveDisposition
{
	HST_RESCUE_CAPTIVE_DISPOSITION_UNKNOWN,
	HST_RESCUE_CAPTIVE_DISPOSITION_HELD,
	HST_RESCUE_CAPTIVE_DISPOSITION_FREED,
	HST_RESCUE_CAPTIVE_DISPOSITION_FOLLOWING,
	HST_RESCUE_CAPTIVE_DISPOSITION_BOARDING,
	HST_RESCUE_CAPTIVE_DISPOSITION_BOARDED,
	HST_RESCUE_CAPTIVE_DISPOSITION_EXTRACTED,
	HST_RESCUE_CAPTIVE_DISPOSITION_KILLED
}

enum HST_ERadioSiteLifecycleState
{
	HST_RADIO_SITE_LIFECYCLE_UNKNOWN,
	HST_RADIO_SITE_LIFECYCLE_ONLINE,
	HST_RADIO_SITE_LIFECYCLE_DESTROYED,
	HST_RADIO_SITE_LIFECYCLE_REBUILDING,
	HST_RADIO_SITE_LIFECYCLE_QUARANTINED
}

enum HST_ERadioSiteTargetOwnership
{
	HST_RADIO_SITE_TARGET_UNRESOLVED,
	HST_RADIO_SITE_TARGET_BORROWED_WORLD,
	HST_RADIO_SITE_TARGET_GENERATED_CAMPAIGN
}

enum HST_EOperationDutyState
{
	HST_OPERATION_DUTY_UNKNOWN,
	HST_OPERATION_DUTY_STAGING,
	HST_OPERATION_DUTY_OUTBOUND,
	HST_OPERATION_DUTY_ON_STATION,
	HST_OPERATION_DUTY_RETURNING_TO_ASSIGNMENT,
	HST_OPERATION_DUTY_RECALL_REQUESTED,
	HST_OPERATION_DUTY_RETURNING_TO_ORIGIN,
	HST_OPERATION_DUTY_EXITING,
	HST_OPERATION_DUTY_RETIRED,
	HST_OPERATION_DUTY_SETTLED
}

enum HST_EOperationEngagementMode
{
	HST_OPERATION_ENGAGEMENT_UNKNOWN,
	HST_OPERATION_ENGAGEMENT_CLEAR,
	HST_OPERATION_ENGAGEMENT_CONTACT,
	HST_OPERATION_ENGAGEMENT_ENGAGED,
	HST_OPERATION_ENGAGEMENT_DISENGAGING
}

enum HST_EOperationMaterializationState
{
	HST_OPERATION_MATERIALIZATION_UNKNOWN,
	HST_OPERATION_MATERIALIZATION_VIRTUAL,
	HST_OPERATION_MATERIALIZATION_MATERIALIZING,
	HST_OPERATION_MATERIALIZATION_PHYSICAL,
	HST_OPERATION_MATERIALIZATION_DEMATERIALIZING,
	HST_OPERATION_MATERIALIZATION_RETIRING,
	HST_OPERATION_MATERIALIZATION_RETIRED
}

enum HST_EOperationPositionAuthority
{
	HST_OPERATION_POSITION_UNKNOWN,
	HST_OPERATION_POSITION_STRATEGIC,
	HST_OPERATION_POSITION_LIVE
}

enum HST_EOperationSettlementState
{
	HST_OPERATION_SETTLEMENT_UNKNOWN,
	HST_OPERATION_SETTLEMENT_OPEN,
	HST_OPERATION_SETTLEMENT_SETTLED
}

enum HST_EOperationTerminalResult
{
	HST_OPERATION_TERMINAL_UNKNOWN,
	HST_OPERATION_TERMINAL_NONE,
	HST_OPERATION_TERMINAL_RECALLED,
	HST_OPERATION_TERMINAL_SPAWN_FAILED,
	HST_OPERATION_TERMINAL_ROUTE_FAILED,
	HST_OPERATION_TERMINAL_DESTROYED,
	HST_OPERATION_TERMINAL_CANCELLED,
	HST_OPERATION_TERMINAL_INVALIDATED,
	HST_OPERATION_TERMINAL_COMPLETED
}

enum HST_ECombatPresenceState
{
	HST_COMBAT_PRESENCE_COLD,
	HST_COMBAT_PRESENCE_HOT,
	HST_COMBAT_PRESENCE_COOLING
}
