enum HST_ECampaignPhase
{
	HST_CAMPAIGN_SETUP,
	HST_CAMPAIGN_ACTIVE,
	HST_CAMPAIGN_WON,
	HST_CAMPAIGN_LOST
}

enum HST_EZoneType
{
	HST_ZONE_TOWN,
	HST_ZONE_OUTPOST,
	HST_ZONE_RESOURCE,
	HST_ZONE_FACTORY,
	HST_ZONE_RADIO_TOWER,
	HST_ZONE_AIRFIELD,
	HST_ZONE_SEAPORT,
	HST_ZONE_POLICE_STATION,
	HST_ZONE_BANK,
	HST_ZONE_HIDEOUT,
	HST_ZONE_MISSION_SITE
}

enum HST_EMissionCategory
{
	HST_MISSION_ASSASSINATION,
	HST_MISSION_CONQUEST,
	HST_MISSION_CONVOY,
	HST_MISSION_DESTROY,
	HST_MISSION_LOGISTICS,
	HST_MISSION_RESCUE,
	HST_MISSION_DYNAMIC,
	HST_MISSION_SUPPORT
}

enum HST_EMissionStatus
{
	HST_MISSION_AVAILABLE,
	HST_MISSION_ACTIVE,
	HST_MISSION_SUCCEEDED,
	HST_MISSION_FAILED,
	HST_MISSION_EXPIRED
}

enum HST_EMissionRuntimeMode
{
	HST_MISSION_RUNTIME_ABSTRACT,
	HST_MISSION_RUNTIME_PHYSICAL_MVP,
	HST_MISSION_RUNTIME_STATE_MACHINE
}

enum HST_EGeneratedSiteType
{
	HST_SITE_TOWN_CENTER,
	HST_SITE_OUTPOST,
	HST_SITE_RESOURCE,
	HST_SITE_FACTORY,
	HST_SITE_RADIO,
	HST_SITE_AIRFIELD,
	HST_SITE_SEAPORT,
	HST_SITE_ROADBLOCK,
	HST_SITE_STASH,
	HST_SITE_CRASHSITE,
	HST_SITE_PATROL,
	HST_SITE_SUPPORT
}

enum HST_EMissionObjectiveType
{
	HST_OBJECTIVE_CLEAR_AREA,
	HST_OBJECTIVE_KILL_TARGET,
	HST_OBJECTIVE_DESTROY_TARGET,
	HST_OBJECTIVE_RECOVER_LOOT,
	HST_OBJECTIVE_DELIVER_SUPPLIES,
	HST_OBJECTIVE_RESCUE_CAPTIVES,
	HST_OBJECTIVE_HOLD_AREA,
	HST_OBJECTIVE_FIND_SITE
}

enum HST_ESupportRequestType
{
	HST_SUPPORT_QRF,
	HST_SUPPORT_PATROL_SWEEP,
	HST_SUPPORT_TRANSPORT,
	HST_SUPPORT_SUPPLY_DROP,
	HST_SUPPORT_SEARCH_AND_DESTROY,
	HST_SUPPORT_SUPPRESSIVE_FIRE,
	HST_SUPPORT_TROOP_LANDING,
	HST_SUPPORT_EVACUATION,
	HST_SUPPORT_AIRSTRIKE_GBU,
	HST_SUPPORT_AIRSTRIKE_UMPK,
	HST_SUPPORT_CRUISE_MISSILE_KH55
}

enum HST_ESupportRequestStatus
{
	HST_SUPPORT_QUEUED,
	HST_SUPPORT_ACTIVE,
	HST_SUPPORT_RESOLVED,
	HST_SUPPORT_CANCELLED
}

enum HST_EEnemyOrderType
{
	HST_ENEMY_ORDER_PATROL,
	HST_ENEMY_ORDER_ROADBLOCK,
	HST_ENEMY_ORDER_QRF,
	HST_ENEMY_ORDER_REBUILD_GARRISON,
	HST_ENEMY_ORDER_COUNTERATTACK,
	HST_ENEMY_ORDER_PETROS_ATTACK,
	HST_ENEMY_ORDER_SUPPORT_CALL
}

enum HST_EEnemyOrderStatus
{
	HST_ENEMY_ORDER_QUEUED,
	HST_ENEMY_ORDER_ACTIVE,
	HST_ENEMY_ORDER_RESOLVED,
	HST_ENEMY_ORDER_ABORTED
}

enum HST_EUndercoverStatus
{
	HST_UNDERCOVER_CLEAR,
	HST_UNDERCOVER_SUSPICIOUS,
	HST_UNDERCOVER_COMPROMISED,
	HST_UNDERCOVER_WANTED
}
