SCR_MissionHeaderCampaign {
 World "{6985327711301100}Worlds/HST_Everon/HST_Everon.ent"
 SystemsConfig "{95C60CD03FA24300}Configs/HST/Persistence/HST_CampaignSystems.conf"
 m_sName "Partisan: Everon"
 m_sAuthor "Partisan contributors"
 m_sDescription "FIA resistance campaign against US occupiers and USSR invaders."
 m_sIcon "{D4E2328F9B870047}Assets/Images/white_h.edds"
 m_sLoadingScreen "{D4E2328F9B870047}Assets/Images/white_h.edds"
 m_sPreviewImage "{D4E2328F9B870047}Assets/Images/white_h.edds"
 m_sDetails "Foundation scenario for the Partisan persistent campaign."
 m_sGameMode "Partisan: Everon"
 m_iPlayerCount 16
 m_eSaveTypes 15
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_iStartingHours 6
 m_fDayTimeAcceleration 2
 m_fNightTimeAcceleration 12
 m_bMapMarkerEnableDeleteByAnyone 1
}
