SCR_MissionHeaderCampaign {
 World "{6985327711301100}Worlds/HST_Everon/HST_Everon.ent"
 m_sName "h-istasi: Everon"
 m_sAuthor "h-istasi contributors"
 m_sDescription "FIA resistance campaign against US occupiers and USSR invaders."
 m_sIcon "{D4E2328F9B870047}Assets/Images/white_h.edds"
 m_sLoadingScreen "{D4E2328F9B870047}Assets/Images/white_h.edds"
 m_sPreviewImage "{D4E2328F9B870047}Assets/Images/white_h.edds"
 m_sDetails "Foundation scenario for the h-istasi persistent campaign."
 m_sGameMode "h-istasi"
 m_iPlayerCount 16
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_iStartingHours 6
 m_fDayTimeAcceleration 2
 m_fNightTimeAcceleration 12
 m_bMapMarkerEnableDeleteByAnyone 1
}
