ActionManager {
 Actions {
  Action HST_CommandMenu {
   InputSource InputSourceSum "69853277113034A1" {
    Sources {
     InputSourceValue "69853277113034A2" {
      FilterPreset "down"
      Input "keyboard:KC_I"
     }
    }
   }
  }
 }
}
